default_platform :ios

platform :ios do
  before_all do |lane, options|
    end
end

lane :pod do
  cocoapods(use_bundle_exec: false)
end

lane :tests do
  pod
  run_tests(workspace: "MT1News.xcworkspace",
            devices: ["iPhone 8"],
            scheme: "MT1News")
end

