name: CI

on: 
  push:
    branches: master, feature/ci
jobs:

  build:

    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        fastlane tests
  